### ISSUE TITLE
Problem beim update von anystores auf die neueste Version

### ISSUE THREAD

**Issue by gassi101** [Tastaturberuf/anyStores#105]
Nach update der anystores für conrtao 3 auf die version für contao 4 bekomme ich folgende Meldung im Install tool. 
```
ALTER TABLE tl_anystores CHANGE latitude latitude DOUBLE PRECISION DEFAULT '0.00' NOT NULL
ALTER TABLE tl_anystores CHANGE longitude longitude DOUBLE PRECISION DEFAULT '0.00' NOT NULL
```

Es passiert einfach nichts - die meldung kommt immer wieder! Man kann neue Standorte aber Eintragen und die Geo Koordinaten kann man berechnen lassen .
Kopieren von Einträgen geht auch nicht - aber das ist nicht so tragisch.

**Comment by Tastaturberuf** [comment]
Ja, das ist nicht wirklich ein Problem. Da mag Doctrine die Definition nicht. 

Welche Fehlermeldung bekommst du beim Kopieren? Mach gerne ein neues Issue dazu auf.
