### ISSUE TITLE
Problem beim kopieren von Einträgen

### ISSUE THREAD

**Issue by gassi101** [Tastaturberuf/anyStores#106]
Beim Kopieren kommt bei mir folgender Fehler wenn ich auf das + Klicke:
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Weinkauff' for key 'pid_name_street_postal_city_country'

**Comment by Tastaturberuf** [comment]
Ich kann den Index löschen, der ist eh sinnlos.

**Comment by Tastaturberuf** [comment]
Fixed in 1.15.1

Danke @gassi101

**Comment by gassi101** [comment]
Danke an dich für die schnelle Bearbeitung - TOP !

**Comment by Tastaturberuf** [comment]
Ich hab schon ganz lange ne Version 2.0 als private bundle. Die ist aber einfach nicht fertig um sie zu veröffentlichen, da war das alles schon gefixt. 🤫
