### ISSUE TITLE
Karte an die Suche koppeln

### ISSUE THREAD

**Issue by Tastaturberuf** [Tastaturberuf/anyStores#19]
Falls die Karte auf einer Suchergebnisseite dargestellt wird, könnten die Ergebnisse auch dort **optional** eingeschränkt werden.

**Comment by bildfaktor** [comment]
Das wäre echt das I-Tüpfelchen bei dieser Erweiterung.

**Comment by Tastaturberuf** [comment]
Added in 1.8.x

Use SearchMap module
