### ISSUE TITLE
different marker for different categories

### ISSUE THREAD

**Issue by overheaddesign** [Tastaturberuf/anyStores#30]
Each category has its own marker will appear on the map, instead of always the same markers for all your categories

**Comment by Tastaturberuf** [comment]
:+1: and override for each location.

**Comment by Tastaturberuf** [comment]
Global -> Category -> Store

**Comment by Tastaturberuf** [comment]
Added in https://github.com/Tastaturberuf/anyStores/releases/tag/1.7.2

Global -> Module -> Category -> Location
