### ISSUE TITLE
Listenausgabe ohne Ländersuche

### ISSUE THREAD

**Issue by tim-bec** [Tastaturberuf/anyStores#31]
Uns fehlt die Möglichkeit eine Ausgabe aller Stores zu generieren. Vor allem über Länder hinweg. In unserem Fall haben wir 25 Einträge in 20 Ländern, eine Übersicht über alle Stores ohne eine Länderspezifische, oder überhaupt eine Suche anstoßen zu müssen wäre super.

**Comment by Tastaturberuf** [comment]
Einfach eine Listenmodul anlegen und Leersuche erlauben anhaken. Fertig. Aber dir wird die Sortierung per PLZ wahrscheinlich nicht gefallen.

**Comment by tim-bec** [comment]
Dabei muss ich trotzdem eine Länderauswahl treffen und sehe immer nur die Einträge des jeweiligen Landes.

**Comment by Tastaturberuf** [comment]
Hm teste das mal fix ohne Suche-Modul. Dann gibt’s kein Dropdown und die Liste sollte komplett sein.

**Comment by tim-bec** [comment]
Leider nein. Auch dabei bleibt es bei dem einen Eintrag aus Deutschland.

**Comment by Tastaturberuf** [comment]
Ich muss mir mal ne internationale Testtabelle anlegen und check das aus.

**Comment by Tastaturberuf** [comment]
Ich weiß was da passiert. Wenn du Contao jetzt beispielsweise auf englisch stellst, dann zeigt er nur noch die englischen Ergebnisse.

**Comment by tim-bec** [comment]
Das kann ich so nicht bestätigen. Weder das umstellen der Sprache im Startpunkt, noch das ändern der Browsersprache hat Auswirkung auf die Liste.

**Comment by Tastaturberuf** [comment]
Bin wieder da, ich schau mir das die Tage an.

**Comment by Tastaturberuf** [comment]
Wir würdest du die gerne sinnvollerweise dann sortiert haben?

**Comment by tim-bec** [comment]
Am liebsten definierbar ;) ansonsten nach den Namen alphabetisch,
absteigend.
Am 24.06.2015 20:02 schrieb "Daniel Jahnsmüller" <notifications@github.com>:

**Comment by Tastaturberuf** [comment]
Added in https://github.com/Tastaturberuf/anyStores/commit/018f38e5550251bbfc22d29b1bd85532dec4a3c5

bzw 1.4.2
