### ISSUE TITLE
Ansprechpartner

### ISSUE THREAD

**Issue by overheaddesign** [Tastaturberuf/anyStores#4]
Neben den Daten Telefonnummer und Fax und so. 
Wäre es gut wenn man auch einen Ansprechpartner eintragen könnte und den auch mit anzeigen lassen kann.

**Comment by Tastaturberuf** [comment]
In Version 1.1 wird es die Möglichkeit geben Ansprechpartner samt kompletter (anderer) Adresse eintragen zu können.

**Comment by Tastaturberuf** [comment]
In 1.8.0 gibt es die Möglichkeit 6 Freitext-Felder zu befüllen. Damit lässt sich das problemlos abbilden.
