### ISSUE TITLE
failed to open stream: anystores or anyStores? (folder name)

### ISSUE THREAD

**Issue by rflx** [Tastaturberuf/anyStores#41]
Hi there,
im getting this Warning when moving the installation from local to production:

`include(/system/modules/anyStores/modules/ModuleAnyStoresSearch.php): failed to open stream: No such file or directory in system/modules/core/library/Contao/ClassLoader.php on line 161`

After renaming the folder `system/modules/anystores` to `system/modules/anyStores` it worked properly. Is this a composer.json source issue that needs to be changed?

Cheers,
rflx

**Comment by Tastaturberuf** [comment]
Thanks, was a typo in the composer.json. :+1:
