### ISSUE TITLE
Nach update von 1.71 nach 1.72 keine Darstellung von anyStores Karte

### ISSUE THREAD

**Issue by pedal123** [Tastaturberuf/anyStores#48]
Chrome-Fehlermeldung:
Uncaught ReferenceError: anystores is not definedloadMap @ anystores.js:10

**Comment by Tastaturberuf** [comment]
Das Template ```mod_anystores_map.html5``` wurde komplett umgebaut. Auch sollte das Modul neu konfiguriert werden. Cache löschen nicht vergessen.
