### ISSUE TITLE
Zu Ihrer Suchanfrage wurden leider keine Ergebnisse gefunden.

### ISSUE THREAD

**Issue by pedal123** [Tastaturberuf/anyStores#49]
1-2 Wochen nach der Installation funktioniert die Suche nicht mehr. Nach Reparatur und Bereinigung wieder 1- 2 Wochen dann wieder Fehler.

anyStores 	1.7.2
Contao Open Source CMS 3.2.20

Details des Datensatzes ID 68 anzeigen
ID: 	68
Datum: 	12.12.2015 10:39
Ursprung: 	Frontend
Kategorie: 	ERROR
Benutzer: 	
Details: 	Failed Request 'https://nominatim.openstreetmap.org/search?q=zwickau&format=json&accept-language=de&limit=1&countrycodes=de' with error '146 Connection refused'
Funktion: 	Tastaturberuf\OpenStreetMap::getLonLat
IP-Adresse: 	92.217.226.0
Browser: 	Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0

Details des Datensatzes ID 69 anzeigen
ID: 	69
Datum: 	12.12.2015 10:39
Ursprung: 	Frontend
Kategorie: 	ERROR
Benutzer: 	
Details: 	Can't find coordinates for 'zwickau'
Funktion: 	Tastaturberuf\AnyStoresModel::findPublishedByAdressAndCountryAndCategory
IP-Adresse: 	92.217.226.0
Browser: 	Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0

Details des Datensatzes ID 70 anzeigen
ID: 	70
Datum: 	12.12.2015 10:39
Ursprung: 	Frontend
Kategorie: 	ERROR
Benutzer: 	
Details: 	Failed Request 'https://nominatim.openstreetmap.org/search?q=zwickau&format=json&accept-language=de&limit=1&countrycodes=de' with error '146 Connection refused'
Funktion: 	Tastaturberuf\OpenStreetMap::getLonLat
IP-Adresse: 	92.217.226.0
Browser: 	Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by Tastaturberuf** [comment]
Sieht aus als würde OSM die Anfrage abweisen. Das kann mehrere Ursachen haben: http://wiki.openstreetmap.org/wiki/Api.openstreetmap.org/Usage_policy

**Comment by Tastaturberuf** [comment]
> Nach Reparatur und Bereinigung...

Und was genau bedeutet das?
