### ISSUE TITLE
Update von 1.6.0 auf 1.8.0 RC1

### ISSUE THREAD

**Issue by overheaddesign** [Tastaturberuf/anyStores#57]
Ich habe geupdatet und dann kam das:
 Fatal error: Call to undefined method Contao\BackendUser::canEditFieldsOf() in /var/www/.../html/system/cache/dca/tl_anystores_category.php on line 297

Was muss man tun, damit es wieder funktioniert?

**Comment by Tastaturberuf** [comment]
1.8.3 gibt es nicht.

**Comment by overheaddesign** [comment]
entschuldige.
Es ist natürlich die 1.8.0-RC1 Version von Anystore
Contao Version ist 3.2.x

**Comment by Tastaturberuf** [comment]
anyStores 1.8.x läuft nun erst ab Contao 3.3 und sollte nach Möglichkeit mit PHP >= 5.5 betrieben werden.

**Comment by overheaddesign** [comment]
naja okay php 5.5 ist drin aber 3.3 muss ich mal schauen wann ich das mache
