### ISSUE TITLE
Contao 3.5.12 - Anystore Installation klappt nicht

### ISSUE THREAD

**Issue by overheaddesign** [Tastaturberuf/anyStores#58]
Ich habe heute versucht AnyStores 1.8.0 zu installieren und dabei kam gleich folgender Fehler:
`[18-May-2016 19:31:22 GMT] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Table 'usr_xxx.tl_anystores_category' doesn't exist 
(SELECT * FROM tl_anystores_category ORDER BY title)' thrown in /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Database/Statement.php on line 295

#0 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()

#1 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Model.php(1082): Contao\Database\Statement->execute(NULL)

#2 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Model.php(981): Contao\Model::find(Array)

#3 /var/www/.../html/projekt-resys/system/modules/anyStores/classes/AnyStoresDcaHelper.php(26): Contao\Model::findAll(Array)

#4 /var/www/.../html/projekt-resys/system/modules/anyStores/dca/tl_form.php(63): Tastaturberuf\AnyStoresDcaHelper::getCategories()

#5 /var/www/...html/projekt-resys/system/modules/core/library/Contao/DcaLoader.php(86): include('/var/www/web......')

#6 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Controller.php(1298): Contao\DcaLoader->load(false)

#7 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/DcaExtractor.php(382): Contao\Controller::loadDataContainer('tl_form')

#8 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/DcaExtractor.php(128): Contao\DcaExtractor->createExtract()

#9 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_form')

#10 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Database/Installer.php(295): Contao\DcaExtractor::getInstance('tl_form')

#11 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Database/Installer.php(111): Contao\Database\Installer->getFromDca()

#12 /var/www/.../html/projekt-resys/system/modules/core/library/Contao/Database/Installer.php(41): Contao\Database\Installer->compileCommands()

#13 /var/www/.../html/projekt-resys/system/modules/repository/classes/RepositoryManager.php(486): Contao\Database\Installer->generateSqlForm()

#14 /var/www/.../html/projekt-resys/system/modules/repository/classes/RepositoryBackendModule.php(153): RepositoryManager->update('database')

#15 /var/www/.../html/projekt-resys/system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()

#16 /var/www/.../html/projekt-resys/system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()

#17 /var/www/.../html/projekt-resys/system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()

#18 /var/www/.../html/projekt-resys/system/modules/core/classes/Backend.php(423): RepositoryManager->generate()

#19 /var/www/.../html/projekt-resys/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')

#20 /var/www/.../html/projekt-resys/contao/main.php(20): Contao\BackendMain->run()

#21 {main}
`

Mach ich da was falsch? Contao Installation ist noch keine 5 Min alt und am Anfang mit Check überprüft worden. PHP 5.5 ist auch drauf.

**Comment by Tastaturberuf** [comment]
Fixed in 1.8.1
