### ISSUE TITLE
Zoom-Level in der Kartenansicht begrenzen/abschaltbar machen und Strasse nicht mehr als Pflichtfeld ausführen

### ISSUE THREAD

**Issue by MichaGi** [Tastaturberuf/anyStores#59]
Damit währe es möglich auch Standorte z.B. bei einer Vereinsliste eintragen zu können, wo keine genaue Anschrift außer der Ort genannt werden sollen. Vielen Dank im Voraus :-)

**Comment by Tastaturberuf** [comment]
Mit folgender Zeile in der unter `system/config/dcaconfig.php`:
```php
$GLOBALS['TL_DCA']['tl_anystores']['fields']['street']['eval']['mandatory'] = false;
```
kannst du das Pflichtfeld ausschalten. 

Die JavaScript-Änderungen sind zur Zeit nur möglich wenn du den Quelltext von `system/modules/anyStores/assets/js/anystores.js` anpasst. Das ist nicht Updatesicher, Version 1.9 wird aber eh nicht ohne manuelle Änderungen zu 1.8 kompatibel sein (Das Templatesystem wurde komplett umgestellt).
