### ISSUE TITLE
Use API key for JavaScript API integration as well.

### ISSUE THREAD

**Issue by fritzmg** [Tastaturberuf/anyStores#60]
Since 22nd of June the API key is also required when embedding the JavaScript API key on the site. Currently the extension embeds the JS API without an API key. See also https://github.com/delahaye/dlh_googlemaps/issues/61

**Comment by DanMan** [comment]
Since the maps are always based on Google Maps, I think this will probably require independent settings for both API keys.

**Comment by DanMan** [comment]
You also need to activate the Google Maps JavaScript API, I think. At least it shows usage in the statistics at Google.

**Comment by Tastaturberuf** [comment]
Added in 1.9 thanks @DanMan
