### ISSUE TITLE
Doesn't actually need Google Maps Geolocation API...

### ISSUE THREAD

**Issue by DanMan** [Tastaturberuf/anyStores#62]
...anymore? At least it didn't work until I activated the `Google Maps Geocoding API` instead. Usage in the API Manager reflected that (no usage of Geolocation, only Geocoding).

This is the error I got:
`{
   "error_message" : "This API project is not authorized to use this API. Please ensure that this API is activated in the APIs Console: https://console.developers.google.com/apis/library?project=_ Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/geocoding_backend?project=_",
   "results" : [],
   "status" : "REQUEST_DENIED"
}`

So the documentation should be updated.

**Comment by Tastaturberuf** [comment]
Fixed in 1.9
