### ISSUE TITLE
Entfernungsberechnung in Version 1.5.3

### ISSUE THREAD

**Issue by overheaddesign** [Tastaturberuf/anyStores#66]
Ich habe die Contao Version 3.2.16 und die Anystores 1.5.3 in Benutzung.
Nun hat mein Kunde das Problem das die Entferungsberechnung für 3.... PLZ falsch berechnet werden.
Also das die Entfernung wird kürzer berechnet als sie eigentlich ist.

Sind in der 1.7.3 Änderungen zu dem Fall eingebaut?
Leider ist es nicht möglich die Contao Version aktuell zu verändern.

![plz suche1](https://cloud.githubusercontent.com/assets/11180194/17694528/8c2f7d0e-63a4-11e6-92ed-c3010097f7e5.png)

**Comment by Tastaturberuf** [comment]
Hallo Michel,

im Changelog steht nichts spezifisches dazu. Da bleibt dir wohl nur testen.

**Comment by Tastaturberuf** [comment]
Das Problem ist eher das "01062" von der Google-API nicht als PLZ in Deutschland erkannt wird.

**Comment by overheaddesign** [comment]
Was kann man dagegen tun?
Google ne Mail schreiben?

**Comment by Tastaturberuf** [comment]
Dein Problem scheint nen Anderes zu sein, kann ich nicht nachvollziehen. Bei mir sind es 6000km wenn ich nur '01062' suche. '01062 Sachsen' passt wieder.

**Comment by overheaddesign** [comment]
Ja aber du siehst ja auch auf dem Bild das ohne Bundesland tortzdem nur 50 km errechnet wird, aber eigentlich sind es 130 km oder so.
Der Längen und Breitengrad wird ja auch ordnetlich errechnet.
mhh ... schon komisch.

**Comment by Tastaturberuf** [comment]
Wie sieht es denn aus wenn eine konkrete Adresse eingegeben wird? Wenn es dann stimmt, sind die Google-Daten nicht OK.
