### ISSUE TITLE
Add support for proxy plugin

### ISSUE THREAD

**Issue by DanMan** [Tastaturberuf/anyStores#67]
If you have to use the [proxy plugin](https://contao.org/de/erweiterungsliste/view/proxy.30030029.de.html) for external requests, the API requests in anyStores to Google or OSM don't work. It should be as simple as:

```
if(class_exists('ProxyRequest'))
    $objRequest = new \ProxyRequest();
else
    $objRequest = new \Request();`
```

inside the 2 API classes.

**Comment by Tastaturberuf** [comment]
Fixed in 2.0

**Comment by DanMan** [comment]
You sure that's right? Notice the NS escape on `\ProxyRequest()` in my code.

**Comment by Tastaturberuf** [comment]
https://github.com/Tastaturberuf/anyStores/blob/2.0.0-dev/src/Tastaturberuf/AnyStores/AnyStores.php#L65
