### ISSUE TITLE
Warning im Backend, wenn kein tableheader ausgewählt ist

### ISSUE THREAD

**Issue by theDyingMountain** [Tastaturberuf/anyStores#71]
Wenn in den Einstellungen kein anystores_tableHeaders gesetzt ist, wird im Contao Backend in der Standortliste eine Fehlermeldung ausgegeben. (siehe Screenshot)
Lösungsvorschlag in tl_anystores.php:
```
        'label' => array
        (
            'fields'      => !empty(\Config::get('anystores_tableHeaders')) ? deserialize(\Config::get('anystores_tableHeaders')) : array('name'),
            'showColumns' => true
        ),
```

![fehler](https://cloud.githubusercontent.com/assets/4446224/19638732/7b943cf2-99d5-11e6-897b-1784dc0d5229.png)

**Comment by Tastaturberuf** [comment]
Fixed
