### ISSUE TITLE
Details GoogleMap Template greift auf fehlerhaftes Logo Objekt zu

### ISSUE THREAD

**Issue by theDyingMountain** [Tastaturberuf/anyStores#72]
Wird ein Standort Logo für einen Standort festgelegt, werden beim Klick auf den Google Marker Fehlermeldungen ausgegeben:
`$this->logo['found']` ist null,
ebenso`$this->logo['path']`
Es wird nur eine Variable `$this->logo` im anystores_details Template gesetzt. welche den Pfad zur Datei enthält.

**Comment by Tastaturberuf** [comment]
Das ganze JavaScript wird grade in der 2.0.0 überarbeitet. Ich sträube mich davor die „alten“ Versionen zu fixen.

**Comment by Tastaturberuf** [comment]
Is natürlich falsch das zu schließen. Muss ja schauen das es in 2.0 läuft :-)

**Comment by uwemock** [comment]
Daran hänge ich gerade. Das Standard-Template anystores_details funktioniert leider nicht. Als Logo-URL wird nur "f" ins HTML ausgegeben.

Es ist ja schön, das in der 2.0 zu korrigieren. Momentan wird mir die Version 1.10.0 angeboten - also scheint es nach mehr als 2 Jahren noch keine 2.0 zu geben. Es wäre schön, wenn es aktuell funtkionieren würde.

**Comment by uwemock** [comment]
Das Problem ist noch weitergehend. Das Land wird mit dem ISO-Kürzel ausgegeben (de, at, ...). In der Listenansicht funktioniert es aber.

**Comment by Tastaturberuf** [comment]
> Daran hänge ich gerade. Das Standard-Template anystores_details funktioniert leider nicht. Als Logo-URL wird nur "f" ins HTML ausgegeben.
> 
> Es ist ja schön, das in der 2.0 zu korrigieren. Momentan wird mir die Version 1.10.0 angeboten - also scheint es nach mehr als 2 Jahren noch keine 2.0 zu geben. Es wäre schön, wenn es aktuell funtkionieren würde.

Sicherlich wäre das schön, es wäre auch schön wenn ich mehr Zeit hätte mich in meiner knappen Freizeit damit zu beschäftigen.

**Comment by Tastaturberuf** [comment]
Sollte gefixt sein in [1.17.4](https://github.com/Tastaturberuf/anyStores/releases/tag/1.17.4)

**Comment by theDyingMountain** [comment]
Danke für den schnellen Fix 😉😀

**Comment by Tastaturberuf** [comment]
Ja ein großer Kunde nutzt das aktuell und debuggt das, wobei die Lösung auch dirty ist.

**Comment by theDyingMountain** [comment]
okay verstehe
