### ISSUE TITLE
Php 7

### ISSUE THREAD

**Issue by garyee** [Tastaturberuf/anyStores#74]
Hallo,

ich habe derzeit ein Projekt auf PHP 7 laufen und da kam ein Fehler, wegen der String Klasse.
Einfach in StringUtil umwandeln in der 
- [ModuleAnyStoresSearchMap](https://github.com/Tastaturberuf/anyStores/blob/master/modules/ModuleAnyStoresSearchMap.php#L76)
- [FrontendAjax](https://github.com/Tastaturberuf/anyStores/blob/11424dd6547c5f9357d9fb4b0361c6af28c65e20/controllers/FrontendAjax.php#L79)
- [tl_anystores.php](https://github.com/Tastaturberuf/anyStores/blob/11424dd6547c5f9357d9fb4b0361c6af28c65e20/dca/tl_anystores.php#L1019)
Wenn ich noch was sehen sollte sag ich Bescheid

**Comment by Tastaturberuf** [comment]
Ja ist im (noch nicht sichtbaren) 2.0-Branch gefixt.
