### ISSUE TITLE
Kategorie in Detaildaten verfügbar machen

### ISSUE THREAD

**Issue by DanMan** [Tastaturberuf/anyStores#75]
Wenn man einen Standort im Detail ausgeben will, dann fehlt die Info zu welcher Kategorie er gehört. Das würde ich aber gerne mit ausgeben.

Derzeit lasse ich die Kategorie nochmal unter Freifeld1 eintragen, was natürlich unnötig und fehleranfällig ist (jemand verschiebt den Standort in andere Kat. und vergisst Freifeld1 anzupassen).

**Comment by Tastaturberuf** [comment]
Die `pid` wird doch mitgegeben. Dann holt man sich über `AnyStoresCategoryModel::findByPid($pid)` die Daten.

**Comment by DanMan** [comment]
Achso, werd's ausprobieren. Danke.
