### ISSUE TITLE
Nicht PHP 7 kompatibel

### ISSUE THREAD

**Issue by BugBuster1701** [Tastaturberuf/anyStores#76]
Klasse String muss durch StringUtil ersetzt werden, mindest Version Contao dann auf 3.5.5 setzen in der composer.json

siehe [Forum](https://community.contao.org/de/showthread.php?65534-Contao-AnyStores-Erweiterung-Weiter-Standort-Http-Error-500&p=431249&viewfull=1#post431249)

**Comment by Tastaturberuf** [comment]
https://github.com/Tastaturberuf/anyStores/issues/74

Aber danke für die Info.

**Comment by Tastaturberuf** [comment]
Hallo @BugBuster1701,

wieso eigentlich genau 3.5.**5**?

**Comment by BugBuster1701** [comment]
Weil in 3.5.5 wichtige PHP7 Anpassungen durchgeführt wurden.
StringUtil gibt es schon seit 3.5.1, aber aus meiner Sicht ist es eben erst ab 3.5.5 sinnvoll Contao auf PHP 7 zu betreiben.
Wenn eine Erweiterung also PHP 7 kompatibel ist so denke ich sollte man auch **mindestens** Contao 3.5.5 haben. Ob die Erweiterung dafür den Nutzer zwingen sollte ist natürlich ne andere Sache.

**Comment by Tastaturberuf** [comment]
Das klingt plausibel, vielen Dank für die ausführliche Info.
