### ISSUE TITLE
Beim eintragen einer url adresse ohne http wird der link falsch generiert

### ISSUE THREAD

**Issue by jdamboeck** [Tastaturberuf/anyStores#77]
Der Link wird als unterseite der aktuellen domain angehängt.

CONTAODOMAIN.FOO/www.eingetragene.url

**Comment by Tastaturberuf** [comment]
Fixed in 1d2357ad758761a99b6461d148daa0ea8d5bd290

Das Verhalten so ist richtig, ich habe allerdings einen deutlichen Hinweis plaziert.
