### ISSUE TITLE
Suche liefert keine Ergebnisse

### ISSUE THREAD

**Issue by Christina81** [Tastaturberuf/anyStores#78]
Ich habe mittels des Moduls anyStores Suche die Suche auf einer Seite eingebunden. Auf der gleichen Seite befinden sich auch die Karte und die Liste. Die Suche liefert aber keine Ergebnisse, obwohl für die gesuchte PLZ ein Eintrag existiert. Habe ich in den Einstellungen etwas falsch gemacht...?
Das sind die Einstellungen für meine Suche:

![grafik](https://user-images.githubusercontent.com/32778309/31559811-45e5898c-b052-11e7-8989-9f366cc5771c.png)

Beispieleintrag:
![grafik](https://user-images.githubusercontent.com/32778309/31559869-782326d4-b052-11e7-9052-0f4fde8765af.png)

Suche nach 46446 liefert keine Ergebnisse:
![grafik](https://user-images.githubusercontent.com/32778309/31559895-8b881fe0-b052-11e7-8928-ee2931247e52.png)

![grafik](https://user-images.githubusercontent.com/32778309/31559911-96c4d8e4-b052-11e7-803d-d11eb64c8da5.png)

**Comment by Tastaturberuf** [comment]
Dann ist vermutlich das Listen-Modul falsch konfiguriert. Steht etwas im Log? Auch das Abfrage-Limit könnte erreicht sein oder der API-Schlüssel falsch konfiguriert. Angaben zur Contao-Version und Version der Erweiterung wären auch hilfreich. 

Das ist ein Thema fürs Contao-Forum, vermutlich kein Fehler der Erweiterung.
