### ISSUE TITLE
Uncaught TypeError: Cannot read property 'zoom' of undefined

### ISSUE THREAD

**Issue by Lelia155** [Tastaturberuf/anyStores#79]
Die Kartenansicht im Frontend lässt sich nicht generieren. 
Fehlermeldung:

Uncaught TypeError: Cannot read property 'zoom' of undefined
at initialize (anystores.js:41)
at XMLHttpRequest.transferComplete (anystores.js:25)

Gibt es hier schon eine Lösung?

**Comment by Tastaturberuf** [comment]
Welche Contao-Version?
Welche anyStores-Version?
Wie sind die entsprechenden Module konfiguriert?
Wurde der Cache gelöscht?

**Comment by Lelia155** [comment]
Contao-Version: 3.5.31
anyStores: die aktuellste die GitHub hergibt (inkl. der aktualisierten Daten aus Nov 2017)
Module: anyStoes Karte via Google Maps API
Cache ist clear

kurze Anmerkung: via Mozi scheint alles zu funktionieren - via Google Chrome, Safari etc. sehe ich allerdings die genannte Fehlermeldung und der Container (section) bleibt im Frontend leer.

**Comment by Tastaturberuf** [comment]
Über Composer installiert, Repository oder manuell? Die aktuelle Github-Master läuft nur unter Contao 4.

**Comment by Tastaturberuf** [comment]
Version 1.10.1 ist die letzte Contao 3 Version: https://github.com/Tastaturberuf/anyStores/releases/tag/1.10.1

**Comment by Lelia155** [comment]
Habe es eben nochmal überprüft bzw. die 1.10.1 installiert. Cache ist geleert und ich habe es an unterschiedlichen Endgeräten mit unterschiedlichen Browsern getestet - es bleibt leider beim gleichen Fehler.

**Comment by Tastaturberuf** [comment]
Wenn das aber Mozilla geht, sollte das überall gehen. Ich selbst nutze die 1.10.1 in diversen Installationen. 
Browser-Cache geleert?

**Comment by Tastaturberuf** [comment]
Per Mail geklärt.

**Comment by Tastaturberuf** [comment]
Lösung: Auf der Seite wo sich das Karten-Modul befindet darf kein Cache eingestellt werden.
