### ISSUE TITLE
Ermitteln der Geokoordinaten aus der Adresse funktioniert nicht

### ISSUE THREAD

**Issue by uwemock** [Tastaturberuf/anyStores#84]
In der Beschreibung der Geokoordinaten-Felder zu einem Standort steht:

"Die geographischen Koordinaten werden benötigt damit der Besucher später nach einem Standort in seiner Nähe suchen kann. Diese beiden Felder werden automatisch beim Speichern ausgefüllt, können aber bei Bedarf manuell korrigiert werden."

Nach dem Speichern steht in den Feldern aber immer "0.000000".

**Comment by uwemock** [comment]
Problem gelöst: Man muß den API-Key für den exakten URL inklusive Protokoll freischalten.
Eine entsprechende Fehlermeldung wäre hilfreich. Das gilt auch für die Frage, was eigentlich ein "Browser-Key" ist. Bei Google gibt es diesen Begriff nicht. Ich habe einfach nochmal den API-Key eingetragen.

**Comment by Tastaturberuf** [comment]
Die Fehlermeldung sollte im Contao-Log stehen. 
Google hat die Begrifflichkeiten mal wieder geändert als sie die gesamte API-Konsole neu strukturiert haben. 

Es sollten unbedingt zwei verschiedene API-Keys verwendet werden:

1. "Server-Key" 
Der Server-Key wird verwendet wenn wenn der Webserver API-Anfragen an Google sendet. Dieser Key sollte auf die IP-Adresse des Servers eingeschränkt werden.

2. "Browser-Key"
Der Browser-Key wird verwendet wenn der Client des Users auf die Google-API zugreift z.B. wenn eine Karte angezeigt wird. Dieser Key sollte zwangsweise auf die Domain des Projekts beschränkt werden. (Die IP des Clients kann man ja nicht kennen)

Wird das nicht getan, kann der Key einfach von Dritten für eigene Projekte verwendet werden und du darfst dafür bezahlen. 

https://developers.google.com/maps/api-key-best-practices#best_practice_list
