### ISSUE TITLE
Kann keine neuen Standorte anlegen

### ISSUE THREAD

**Issue by wernerjoss** [Tastaturberuf/anyStores#85]
hallo,
contao 4.4.55, neue Installation incl. anystores plugin.
Beim Versuch, einen neuen Standort anzulegen, escheint folgendes:

Internal Server Error
Was ist das Problem?
An exception occurred while executing 'INSERT INTO tl_anystores (`pid`, `tstamp`) VALUES ('1', 0)': SQLSTATE[HY000]: General error: 1364 Field 'longitude' doesn't have a default value

Dasselbe bei einer bestehenden Installation mit ca. 250 Standorten (die alle richtig angezeigt wedern und auch bearbeitet werden können).
gibt es eine Abhilfe ?

**Comment by stefansl** [comment]
Probier mal als Quickfix in   https://github.com/Tastaturberuf/anyStores/blob/48d1d7370708f629ee753d1ffbc98702ec50900c/dca/tl_anystores.php#L459          
`'sql' => "float(10,6) NOT NULL"`
`'sql' => "float(9,2) unsigned NULL default NULL"`
zu ändern. Das Gleiche darunter beim Feld latitude.

Danach einmal den Anwendungscache löschen und nochmal das Installtool starten.

**Comment by stefansl** [comment]
Achtung! Hatte ein paar Fehler drin, hab's geändert ...

**Comment by wernerjoss** [comment]
Ok, super, danke, das ist die Lösung 😄 .
ich habe den Fix jetzt eingefügt und einen Pull Request gestartet, mal sehen ob sich da noch einer drum kümmert...

**Comment by Tastaturberuf** [comment]
Danke für eure Hilfe :) Fixed in #86
