### ISSUE TITLE
Feld für ID zur Sortierung ergänzen

### ISSUE THREAD

**Issue by sl4Jke** [Tastaturberuf/anyStores#89]
Gibt es eine Möglichkeit ein Feld zum eintragen einer Nummer zur Sortierung der einzelnen Elemente hinzuzufügen?

Aktuell muss ich die fortlaufend automatisch vergebene ID direkt in der Datenbank ändern oder die einzelnen Standorte direkt in der Reihenfolge anlegen, wie sie am Ende platziert werden sollen.

Vielen Dank.

**Comment by Tastaturberuf** [comment]
Hallo @sl4Jke 

du kannst einfach eines der 6 Freifelder im Backend benutzen. Im Frontend-Modul gibst du unter `Sortierreihenfolge` dann einfach `freeField1` ein.

**Comment by sl4Jke** [comment]
Hallo @Tastaturberuf 

vielen Dank für die schnelle Rückmeldung. Hat Funktioniert.
